### ISSUE TITLE
Gendered names don't generate properly for localized fakerators.

### ISSUE THREAD

**Issue by teokk1** [icebob/fakerator#171]
When using a Fakerator with a locale, the name functions (getFIrstNameF/getFirstNameM) return both male and female names. 

Here's a fiddle demonstrating this behavior:

https://jsfiddle.net/70syxpqw/2/

**Comment by icebob** [comment]
The reason is that some locale data doesn't contain separated male/female data, only just `firstName`.
E.g. in de-DE: 
https://github.com/icebob/fakerator/blob/f8cb00bd87208d2108a35cdb4920fdf0e18c6c03/lib/locales/de-DE/names/index.js#L1-L12

in default eng: 
https://github.com/icebob/fakerator/blob/f8cb00bd87208d2108a35cdb4920fdf0e18c6c03/lib/locales/default/names/index.js#L1-L24

And in this case, Fakerator uses the same firstName list for both.

**Comment by teokk1** [comment]
As far as I can see they're ordered by gender in the array - first all the male names then all the female names. It shouldn't be a hard fix. I could give making a PR a shot over the weekend, if you'd like?

**Comment by icebob** [comment]
ok, it would be great.
